import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Cards from "../components/Cards";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className="pb-[4rem]">
      <Head>
        <title>Smartcodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex justify-center items-center h-[20rem]">
        <h1 className="font-bold text-[3rem] sm:text-[5rem] text-center">
          <span className="text-[#f26857]">OUR</span> PROJECTS
        </h1>
      </div>
      <Cards>
        <Card
          img="/block.png"
          title="Block & Build"
          link="blockandbuild.com.pk"
        />
        <Card
          img="/starpoint.png"
          title="Starpoint 360"
          link="starpoint360.com"
        />
        <Card img="/qari.png" title="Qari Shehzeeb" link="qarishehzeeb.com" />
        <Card
          img="/drilling.png"
          title="Continental Drilling Company"
          link="cdcpk.biz"
        />
        <Card img="/taqwa.png" title="Taqwa Apps" link="taqwaapps.com" />
        <Card img="/moev.png" title="Moev Energy" link="moevenergy.com.au" />
        <Card
          img="/sms.png"
          title="School Management System"
          link="portal.edenedu.info"
        />
        <Card
          img="/techbook.png"
          title="Techbook (Under Construction)"
          link="techbook1.netlify.app"
        />
        <Card
          img="/tcs.png"
          title="TCS (Under Construction)"
          link="tcsweb.netlify.app"
        />
      </Cards>
    </div>
  );
}
